### ISSUE TITLE
你好，大佬，刚好看到这个流程图，请教个问题

### ISSUE THREAD

**Issue by vincent-cong** [pdsuwwz/celonis-vue-demo#1]
想参考下你这个流程图 ，请问现在安装下来，运行出来是空白 是什么情况？可以帮忙指导下么 非常感谢

**Comment by pdsuwwz** [comment]
您好，运行出来是空白，有可能您访问的是根路由 '/' 页面，这个页面本身没有任何东西的

**Comment by pdsuwwz** [comment]
可以另参照这个文件：https://github.com/pdsuwwz/celonis-vue-demo/blob/master/src/router/routes.js

这里面才是真正的路由

**Comment by pdsuwwz** [comment]
这个 demo 东西比较杂，不知道您是要参考哪一部分，我本地跑了下是可以正常运行的，给您几个参考的路由 :)

http://localhost:8080/process/celonis-ball-demo

http://localhost:8080/process/celonis-move-demo

http://localhost:8080/process/dagre-d3/celonis-dagre-d3-live-demo

**Comment by vincent-cong** [comment]
好的 谢谢了  里面的路由都是基础的DEMO

**Comment by vincent-cong** [comment]
![image](https://user-images.githubusercontent.com/15900538/141929389-9af93b86-9eeb-4f0f-8b0f-45fdf7be5dbe.png)

请问这个流程图的DEMO有么？

**Comment by vincent-cong** [comment]
看到 http://localhost:8080/process/dagre-d3/celonis-dagre-d3-live-demo  这个了  非常感谢

**Comment by pdsuwwz** [comment]
> ![image](https://user-images.githubusercontent.com/15900538/141929389-9af93b86-9eeb-4f0f-8b0f-45fdf7be5dbe.png)
> 
> 请问这个流程图的DEMO有么？

类似这张图的，我记得在 [dagre-d3](https://github.com/pdsuwwz/celonis-vue-demo/tree/master/src/modules/Process/pages/dagre-d3)  目录下有几个例子，应该可以作为参考

**Comment by pdsuwwz** [comment]
> 看到 http://localhost:8080/process/dagre-d3/celonis-dagre-d3-live-demo 这个了 非常感谢

不客气，希望对您有帮助 :)
